const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
(async()=>{
  const browser=await chromium.launch({channel:'chrome',headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1050}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:8001');
  await page.locator('#login-form input[name=password]').fill('UI-test-password-2026');
  await page.locator('#login-form button').click();
  await page.locator('.workspace-checks').waitFor();
  await page.locator('nav a[href="#settings"]').click();
  await page.locator('#rules-form input[name=version]').fill('ui-verified-20260912');
  await page.locator('#rules-form [name=confirmed]').check();
  await page.locator('#rules-form button[type=submit]').click();
  await page.getByText('规则已保存，后续分析使用此版本',{exact:true}).waitFor();
  await page.reload();
  await page.locator('#rules-form').waitFor();
  assert.equal(await page.locator('#rules-form input[name=version]').inputValue(),'ui-verified-20260912');
  assert(await page.locator('#rules-form [name=confirmed]').isChecked());
  await page.locator('nav a[href="#documents"]').click();
  await page.getByRole('button',{name:'手动录入',exact:true}).click();
  await page.locator('#import-form [name=title]').fill('未提交的草稿测试');
  await page.locator('#import-form [name=body]').fill('草稿不会被导航操作丢失，也不会被发送到服务器。');
  await page.locator('nav a[href="#overview"]').click();
  await page.locator('.workspace-checks').waitFor();
  await page.locator('nav a[href="#documents"]').click();
  await page.locator('#import-form [name=title]').waitFor();
  assert.equal(await page.locator('#import-form [name=title]').inputValue(),'未提交的草稿测试');
  await page.locator('#document-filter [name=policy]').selectOption('external');
  await page.locator('#document-filter button').first().click();
  await page.getByRole('heading',{name:'暂无待分析资料'}).waitFor();
  await page.locator('#reset-doc-filter').click();
  await page.locator('tbody tr').first().waitFor();
  await page.locator('nav a[href="#events"]').click();
  await page.locator('.event-link').first().click();
  await page.locator('#review-form [name=note]').fill('新增复核历史测试');
  await page.locator('#review-form button[type=submit]').click();
  await page.getByText('复核意见已保存',{exact:true}).waitFor();
  await page.locator('.review-history summary').click();
  await page.locator('.review-history article').filter({hasText:'新增复核历史测试'}).first().waitFor();
  await page.locator('.back-link').click();
  const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('link',{name:'导出当前筛选 CSV'}).click()]);
  assert.equal(download.suggestedFilename(),'risk-events.csv');
  await page.locator('nav a[href="#jobs"]').click();
  await page.locator('#job-filter select').selectOption('failed');
  assert.match(await page.locator('#job-match').textContent(),/当前显示 0 条/);
  await page.locator('nav a[href="#settings"]').click();
  await page.locator('#rules-form').waitFor();
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.screenshot({path:'qa/mobile-settings.png',fullPage:true});
  await browser.close();
  assert.deepEqual(errors,[]);
  console.log('Feature workflow passed: rules persistence, draft recovery, document filters, review history, CSV download, task filters, mobile settings.');
})().catch(e=>{console.error(e);process.exit(1)});
