const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('fs');
const path = require('path');
(async()=>{
  fs.mkdirSync('qa',{recursive:true});
  const browser=await chromium.launch({channel:'chrome',headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1050}});
  const errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('console',m=>{if(m.type()==='error'&&!/status of (401|409)/.test(m.text()))errors.push(m.text());});
  await page.goto('http://127.0.0.1:8001');
  await page.locator('#login-form').waitFor();
  await page.locator('input[name=password]').fill('UI-test-password-2026');
  if(await page.locator('input[name=confirm]').count())await page.locator('input[name=confirm]').fill('UI-test-password-2026');
  await page.locator('#login-form button').click();
  await page.getByRole('heading',{name:'风险总览',exact:true}).waitFor();
  if(await page.locator('[data-demo]').count()){
    await page.locator('[data-demo]').click();
    await page.getByText('示例：工业园区供电中断影响生产',{exact:true}).waitFor();
  }
  await page.locator('#notice').waitFor({state:'hidden'});
  await page.screenshot({path:'qa/desktop-overview.png',fullPage:true});
  // Charts are entry points into the same event filters used for business review.
  await page.locator('[data-scope="demo"]').click();
  await page.locator('.stat.red').click();
  await page.locator('#event-filter').waitFor();
  if(await page.locator('select[name=level]').inputValue()!=='red')throw new Error('Risk tile did not apply its level');
  if(await page.locator('[data-scope="demo"]').getAttribute('aria-pressed')!=='true')throw new Error('Chart navigation lost data scope');
  await page.locator('tbody tr').first().waitFor();
  if(await page.locator('tbody .badge.red').count()!==await page.locator('tbody tr').count())throw new Error('High-risk filter returned another level');
  await page.locator('select[name=level]').selectOption('orange');
  await page.locator('#event-filter button[type=submit]').click();
  await page.waitForURL(/level=orange/);
  await page.reload();
  await page.locator('#event-filter').waitFor();
  if(await page.locator('select[name=level]').inputValue()!=='orange')throw new Error('Reload lost the selected filter');
  await page.screenshot({path:'qa/desktop-events.png',fullPage:true});
  await page.locator('nav a[href="#overview"]').click();
  await page.locator('.signal-network a').first().waitFor();
  await page.locator('.signal-network a').first().click();
  await page.locator('#event-filter').waitFor();
  const selectedCategory=await page.locator('select[name=category]').inputValue();
  if(!selectedCategory)throw new Error('Category network did not set the filter');
  await page.locator('tbody tr').first().waitFor();
  for(const category of await page.locator('tbody tr td:nth-child(3)').allTextContents())if(category.trim()!==selectedCategory)throw new Error('Category filter returned an unrelated event');
  await page.locator('nav a[href="#overview"]').click();
  await page.locator('.review-number').click();
  await page.locator('#event-filter').waitFor();
  if(await page.locator('select[name=review]').inputValue()!=='pending')throw new Error('Review shortcut did not apply pending filter');
  await page.locator('nav a[href="#overview"]').click();
  await page.getByRole('heading',{name:'风险总览',exact:true}).waitFor();
  await page.getByText('示例：工业园区供电中断影响生产',{exact:true}).click();
  await page.getByRole('heading',{name:'判断依据与来源'}).waitFor();
  await page.screenshot({path:'qa/desktop-detail.png',fullPage:true});
  await page.getByRole('button',{name:'定位原文',exact:true}).click();
  await page.locator('#source-content mark').waitFor();
  await page.screenshot({path:'qa/desktop-source.png',fullPage:true});
  await page.getByRole('button',{name:'关闭',exact:true}).click();
  await page.locator('#review-form select').selectOption('accepted');
  await page.locator('#review-form textarea').fill('浏览器自动化测试复核。');
  await page.getByRole('button',{name:'保存复核意见'}).click();
  await page.waitForFunction(()=>document.querySelector('#review-form textarea')?.value==='浏览器自动化测试复核。');
  await page.locator('nav a[href="#documents"]').click();
  await page.getByRole('button',{name:'手动录入',exact:true}).click();
  await page.locator('#import-form input[name=title]').fill('浏览器测试资料 '+Date.now());
  await page.locator('#import-form textarea').fill('这是浏览器自动化验证的合成资料，某园区因设备故障导致供电中断。');
  await page.getByRole('button',{name:'保存待分析资料',exact:true}).click();
  await page.locator('.success').waitFor();
  await page.locator('#notice').waitFor({state:'hidden'});
  await page.screenshot({path:'qa/desktop-import.png',fullPage:true});
  await page.locator('[data-analyze]').first().click();
  await page.locator('#notice').filter({hasText:'尚未配置'}).waitFor();
  await page.locator('nav a[href="#knowledge"]').click();
  await page.getByRole('heading',{name:'知识库',exact:true}).waitFor();
  await page.locator('#import-form input[name=title]').fill('浏览器供电应急知识 '+Date.now());
  await page.locator('#import-form textarea').fill('供电设施故障时，应核实停电范围，检查应急供电设施。');
  await page.getByRole('button',{name:'导入知识库',exact:true}).click();
  await page.locator('.success').waitFor();
  await page.locator('#knowledge-search input').fill('供电故障');
  await page.getByRole('button',{name:'检索资料',exact:true}).click();
  await page.locator('.search-hit').first().waitFor();
  await page.locator('nav a[href="#settings"]').click();
  await page.getByRole('heading',{name:'模型与规则',exact:true}).waitFor();
  await page.locator('#notice').waitFor({state:'hidden'});
  await page.screenshot({path:'qa/desktop-settings.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.locator('nav a[href="#overview"]').click();
  await page.getByRole('heading',{name:'风险总览',exact:true}).waitFor();
  await page.screenshot({path:'qa/mobile-overview.png',fullPage:true});
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
  if(overflow)throw new Error('Mobile viewport overflow');
  await page.locator('nav a[href="#documents"]').click();
  await page.getByRole('heading',{name:'资料与导入',exact:true}).waitFor();
  await page.screenshot({path:'qa/mobile-import.png',fullPage:true});
  if(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth))throw new Error('Mobile import overflow');
  await browser.close();
  fs.writeFileSync('qa/browser-results.json',JSON.stringify({status:errors.length?'failed':'passed',errors,checks:['login','demo load','risk tile filter','data scope preserved','filter survives reload','category network filter','pending review shortcut','event detail','source quote highlight','review save','manual import','unconfigured model block','knowledge import and search','settings','desktop and mobile layout']},null,2));
  if(errors.length)throw new Error(errors.join('\n'));
  console.log('Browser workflow passed; desktop/mobile screenshots saved.');
})().catch(e=>{console.error(e);process.exit(1)});
