const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
const {execFileSync}=require('node:child_process');
const path=require('node:path');
(async()=>{
  const browser=await chromium.launch({channel:'chrome',headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1050}});const errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:8001');
  await page.locator('#login-form input[name=password]').fill('UI-test-password-2026');
  await page.locator('#login-form button').click();await page.locator('.workspace-checks').waitFor();
  await page.goto('http://127.0.0.1:8001/#events?demo=demo&level=red');
  await page.getByRole('link',{name:'生成风险简报',exact:true}).click();
  await page.locator('.report-event').waitFor();assert.equal(await page.locator('.report-event').count(),1);
  assert.match(await page.locator('.report-paper').textContent(),/虚构演示/);
  await page.screenshot({path:'qa/desktop-report.png',fullPage:true});
  await page.pdf({path:'qa/risk-report-print.pdf',format:'A4',printBackground:true,preferCSSPageSize:true});
  await page.locator('#report-filter [name=demo]').selectOption('real');
  await page.locator('#report-filter button').click();await page.getByText('当前范围没有风险事件。此处为空不代表不存在投资风险，请核对资料覆盖范围。',{exact:true}).waitFor();
  await page.locator('nav a[href="#documents"]').click();
  await page.locator('[data-analyze]').first().click();await page.locator('#preflight-panel').waitFor();
  assert(await page.locator('#confirm-analysis').isDisabled());
  await page.screenshot({path:'qa/desktop-preflight.png',fullPage:true});
  await page.locator('#close-preflight').click();
  await page.locator('#document-filter [name=policy]').selectOption('local');await page.locator('#document-filter button').first().click();
  await page.waitForURL(/policy=local/);await page.reload();await page.locator('#document-filter').waitFor();
  assert.equal(await page.locator('#document-filter [name=policy]').inputValue(),'local');
  const result=await page.request.post('http://127.0.0.1:8001/api/documents',{headers:{'X-Requested-With':'risk-workbench'},data:{title:'排队取消验证（合成）',body:'这份资料只用于隔离测试队列的取消操作。'}});
  const id=(await result.json()).id;
  const db=path.resolve('qa/release-20260913/risk.db');
  const job=execFileSync(path.resolve('.venv/Scripts/python.exe'),['-c','import sqlite3,sys; db=sqlite3.connect(sys.argv[1]); c=db.execute("INSERT INTO jobs(document_id,status,created_at) VALUES (?,\'queued\',\'2026-09-13T00:00:00Z\')",(int(sys.argv[2]),)); db.commit(); print(c.lastrowid)',db,String(id)],{encoding:'utf8'}).trim();
  await page.goto('http://127.0.0.1:8001/#jobs?q='+job);
  await page.locator('[data-cancel-job="'+job+'"]').click();
  await page.getByText('排队任务已取消，可稍后重新提交。',{exact:true}).waitFor();
  await page.locator('tbody .badge.cancelled').waitFor();
  await page.screenshot({path:'qa/desktop-jobs.png',fullPage:true});
  await page.goto('http://127.0.0.1:8001/#report?demo=demo&level=red');await page.locator('.report-event').waitFor();
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.screenshot({path:'qa/mobile-report.png',fullPage:true});
  await browser.close();assert.deepEqual(errors,[]);
  console.log('Release workflows passed: report scope, print PDF, preflight blocking, persisted filters, queued cancellation and mobile report.');
})().catch(e=>{console.error(e);process.exit(1)});
