const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
(async()=>{
  const browser=await chromium.launch({channel:'chrome',headless:true});
  try{
    const page=await browser.newPage({viewport:{width:1440,height:1000}});
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    await page.goto('http://127.0.0.1:8001');
    await page.locator('input[name=password]').fill('UI-test-password-2026');
    await page.locator('#login-form button').click();
    await page.locator('.analysis-board').waitFor();
    await page.locator('#toggle-navigation').click();
    assert.equal(await page.locator('#toggle-navigation').getAttribute('aria-expanded'),'false');
    await page.locator('#toggle-navigation').click();
    await page.locator('[data-scope=demo]').click();
    await page.locator('[data-chart-view=rank]').click();
    await page.locator('.rank-row').first().waitFor();
    assert.equal(await page.locator('.signal-canvas').isVisible(),false);
    await page.locator('.rank-row').first().click();
    assert.ok(await page.locator('select[name=category]').inputValue());
    await page.locator('#clear-filter').click();
    await page.locator('[data-preview]').first().waitFor();
    const first=page.locator('[data-preview]').first();
    const firstId=await first.getAttribute('data-preview');
    await first.click();
    await page.locator('#inspection-review').waitFor();
    await page.locator('#inspection-review textarea').fill('分栏核验草稿保留检查');
    await page.locator('[data-preview]').nth(1).click();
    await page.locator('#inspection-review').waitFor();
    await page.locator(`[data-preview="${firstId}"]`).click();
    await page.locator('#inspection-review').waitFor();
    assert.equal(await page.locator('#inspection-review textarea').inputValue(),'分栏核验草稿保留检查');
    await page.locator('.inspection-panel [data-source]').first().click();
    await page.locator('#source-content mark').waitFor();
    await page.locator('#close-source').click();
    const scope=page.url();
    await page.locator('#inspection-review select').selectOption('accepted');
    await page.locator('#inspection-review button[type=submit]').click();
    await page.locator('#inspection-feedback .success').waitFor();
    assert.equal(page.url(),scope);
    const saved=await page.request.get(`http://127.0.0.1:8001/api/events/${firstId}`);
    assert.equal((await saved.json()).review_note,'分栏核验草稿保留检查');
    await page.evaluate(()=>{document.activeElement?.blur();window.scrollTo(0,0);});
    await page.screenshot({path:'qa/desktop-verification-workspace.png',fullPage:true});
    await page.setViewportSize({width:390,height:844});
    await page.screenshot({path:'qa/mobile-verification-workspace.png',fullPage:true});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    await page.locator('nav a[data-nav=documents]').click();
    await page.locator('.library-workbench').waitFor();
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    await page.setViewportSize({width:1440,height:1000});
    await page.screenshot({path:'qa/desktop-library-workspace.png',fullPage:true});
    assert.deepEqual(errors,[]);
    console.log('Workspace passed: navigation, chart ranking, category filter, inspection drafts, source tracing, persisted review, responsive layouts.');
  }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
